services:  
    template:
        build: ./apps/template
        volumes:
            - ./apps/template/src:/root/template
        tty: true
        restart: always
    
    group:
        build: ./apps/group
        volumes:
            - ./apps/group/src:/root/group
        tty: true
        restart: always

    auth:
        build: ./auth
        volumes:
            - ./auth/src:/root/auth
        tty: true
        restart: always

    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        ports:
            - "8447:80"
        volumes:
            # NGINXのコンフィグファイルをホストOSから、ゲストOSに連結する
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/etc/nginx/keys
            - ./nginx/statics/public:/etc/nginx/static/statics
        tty: true

    redis:
        image: "redis:latest"
        ports:
            - "16379:6379"
        volumes:
            - "./databases/MainRedis:/data"
        restart: always
    
    aredis:
        image: "redis:latest"
        ports:
            - "26379:6379"
        volumes:
            - "./databases/AuthRedis:/data"
        restart: always
