FROM golang:1.22.3-bookworm as develop

RUN apt update

WORKDIR /root/auth

COPY ./src .

RUN ["chmod","+x","./setup.sh"]
RUN ["bash","./setup.sh"]

# go のパッケージをダウンロードする
RUN go mod download

# # ARG CGO_ENABLED=0
# # 64bit linux用にビルドする
# ARG GOOS=linux
# ARG GOARCH=amd64
# # ビルド成果物にデバック情報が含まれないようにする
# # RUN go build -x -ldflags '-s -w' -o ./server

# # 実行するコマンド
# CMD ["go","run","-x","."]

# FROM debian:stable-slim as runner

# WORKDIR /app

# RUN addgroup --system --gid 10001 nonroot
# RUN adduser --system --uid 10001 nonroot

# COPY --from=develop --chown=nonroot:nonroot /root/auth/server .
# COPY --from=develop --chown=nonroot:nonroot /root/auth/.env .
# COPY --from=develop --chown=nonroot:nonroot /root/auth/server.key .
# COPY --from=develop --chown=nonroot:nonroot /root/auth/server.crt .
# COPY --from=develop --chown=nonroot:nonroot /root/auth/statics/ ./statics
# # ENTRYPOINT ["./server"]

# USER nonroot

# CMD [ "bash" ]